---
title: "Unidad de Métodos y Acceso a Datos"
output:
  html_document:
    toc: false
    toc_float: false

---

<br />  

    
La Unidad de Métodos y Acceso a Datos de la Facultad de Ciencias Sociales se constituye como un espacio de producción, organización y difusión de datos y abordajes metodológicos relativos a la realidad socioeconómica y política del país, la región y el mundo. Lo hace ofreciendo a los usuarios un observatorio socioeconómico y político del Uruguay y de Uruguay en la Región y el Mundo, un sistema de búsqueda y construcción personalizada de tablas y gráficos en base a motores generados desde bases consolidadas por los equipos de la UMAD y un repositorio de acceso libre a micro-datos con sus fichas técnicas, metadatos y formularios así como vínculos a recursos nacionales e internacionales (motores de búsqueda de datos, sistemas de consulta y micro-datos). Asimismo suma a estas funciones la disponibilización de plataformas de gestión y acceso a centros de producción de información y sus infraestructuras (sala Gesel y Centro de Llamadas) y el apoyo a la consolidación de nuevas líneas y modos de investigación (Laboratorio de Experimentos). Finalmente la UMAD busca colaborar en el desarrollo y debate sobre técnicas e innovaciones metodológicas y sobre los desafíos y herramientas para promover la enseñanza y pedagogía del vector metodológico en el diseño curricular de la oferta educativa de la Facultad de Ciencias Sociales.

En esta iniciativa sobre el COVID19 la UMAD busca aportar a la difusión del conocimiento e información respecto al coronavirus y al COVID19 en Uruguay y el mundo. Ofrece el observatorio COVID19, el panorama de la vulnerablidad social frente a la epidemia, la oferta de documentos sociales, económicos y metodológicos compilados desde la UMAD en torno a COVID19 y un sistema de vínculos a recursos nacionales e internacionales en la materia.

Para ingresar a la página general de la UMAD, haga click [aquí](https://umad.cienciassociales.edu.uy/).    

<br />
    <br />
        <br />

#### **Responsable del proyecto**  

Fernando Filgueira

#### **Equipo**  

Fabricio Carneiro  
Nicolás Schmidt  
Jimena Pandolfi  


  <br />
    <br />
      <br />
     
__Si encuentra errores, omisiones, inconsistencias o problemas sería de gran ayuda que nos lo hagan saber por algunos de nuestros canales de conatcto.__    



