---
title: "Datos"
output:
  html_document:
    toc: false
 

---

Los datos con los que se elaboraron los distintos módulos de este sito provienen de distintas fuentes. La UMAD elaboró, a partir de distintas bases de datos una base de datos que tiene un conjunto las principales variables que hasta el día de hoy hay disponible sobre el estado de la pandemia de COVID19.    

<br />


+ __Observatorio COVID19__: la base correspondiente al módulo COVID19 provienen de las siguientes fuentes:

    * La base estructural es la del paquete de R [{tidycovid19}](https://github.com/joachim-gassen/tidycovid19) que provee un merge de datos de las siguientes fuentes (JHU, Google, Apple, wbank, OWD). Esta base tiene una estructura de día-país.
    
    * Adicionalmente a esta base se cargaron datos [Our World in Data COVID19](https://ourworldindata.org/coronavirus) (cantidad de test, personas mayores de 65 y 75 años, pib y pobreza)
    
    * Para el caso de Uruguay en la base de tidycovid19 encontramos algunas inconsistencias. Para las principales variables (cantidad de casos, muertes y recuperados) los cargamos desde la base de datos del [Grupo Uruguayo Interdisciplinario de Análisis de Datos de COVID‑19](https://guiad-covid.github.io/).
<br />

Puede descargar la base en este [__link__](). Esta base de datos y los gráficos del módulo __Observatorio COVID19__ se actualizan a medianoche diariamente.

<br />    

+ __Observatorio de vulnerabilidad social__: la base correspondiente al módulo de vulnerabilidad social provienen de las siguientes fuentes:

    * Encuesta Continua de Hogares
    * Observatorio Social del Mides
    * Banco de Previsión Social



<br />

Puede descargar los datos en este [__link__](). 




```{r, echo = FALSE, eval = FALSE}
library(knitr)
library(kableExtra)
library(tidycovid19)
vd <- tidycovid19_variable_definitions
ds <- tidycovid19_data_sources
data_info <- dplyr::left_join(vd, ds, by = c(var_source = "id"))
p <- data_info[, 1:3]
p %>%
  kable() %>%
  kable_styling()
```


